unstable_features = true
# set so that executing rustfmt (instead of cargo fmt) respects edition
edition = "2021"

condense_wildcard_suffixes = true
empty_item_single_line = true
enum_discrim_align_threshold = 20
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
group_imports = "StdExternalCrate"
hard_tabs = true
hex_literal_case = "Upper"
imports_granularity = "Item"
match_block_trailing_comma = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
reorder_imports = true
struct_field_align_threshold = 20
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
